# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Patrick Ding
email: patrickding00@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Patrick Ding's website. A blog with my projects and information about me.
baseurl: ""#"/blog" # the subpath of your site, e.g. /blog
url: "http://delimited0.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  delimited0
timezone: America/New_York
scholar:
  style: apa
  locale: en

  sort_by: year
  order: ascending

  source: ./_bibliography
  bibliography: references.bib

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"  

# Build settings
markdown: kramdown
